### ISSUE TITLE
Be all In on re-com layout

### ISSUE THREAD

**Issue by mike-thompson-day8** [gadfly361/reagent-seed#3]
Thanks Matthew.  I'm very grateful this template exists!  

I have a comment on the re-com side of things:  be sure to use h-box and v-box for all layout.  Stay away from using [:divs] and [:spans]. 

See "Be all In"  in:
http://re-demo.s3-website-ap-southeast-2.amazonaws.com/#/layout

```
(defn page []
  [v-box                                           ;;   <--- not  [:div]
   :gap "10px"
   [re-com/title 
    :label "Welcome to the Home Page"
    :level :level1]
   [re-com/hyperlink-href 
    :label "go to About Page"
    :href "#/about"]])
```

**Comment by gadfly361** [comment]
:+1:  Will push out a new version tomorrow morning.

Hoping to turn reagent-seed into an opinionated template that favors day8 libs and utilize their intended harmony, so any input is appreciated!  Let me know if you'd like to see anything changed, added, etc.

**Comment by mike-thompson-day8** [comment]
Thanks!  Will do.

**Comment by mike-thompson-day8** [comment]
I'm adding a link to this template in re-com docs.

**Comment by rej156** [comment]
I recommend a boot runtime version of this template?
Also if it doesn't include figwheel for now, also remove the cljstime dep?

**Comment by gadfly361** [comment]
@mike-thompson-day8 thanks!

@rej156 
* Unfortunately, I don't have plans to include boot
* Will work on adding figwheel!
    * If someone beats me to it, please send a PR :)
* Ah, it appears cljs-time is no longer recommended with v0.4.1 (https://github.com/Day8/re-com/commit/68a06083c58cf168f94f3b4b6fedb7f45dccf6a9?diff=unified). Will remove in next update.

**Comment by mike-thompson-day8** [comment]
In terms of using re-com's layout component (h-box and v-box), note also this comment:
https://github.com/Day8/re-com/blob/master/src/re_demo/core.cljs#L185-L187

**Comment by gadfly361** [comment]
@mike-thompson-day8 updated template in master branch, but haven't pushed to clojars yet. Figured I'd wait on the next version of re-com, as well as give you a chance to look at it.

**Comment by mike-thompson-day8** [comment]
I'd suggest pushing to clojars now, because those changes are fairly important for someone getting going. 

There is likely to be a fairly steady stream of incremental changes to re-com over the next few weeks. We still have one or two things to finish off, and no doubt there will be more feedback.  So if we wait for the next release we could be perpetually waiting for a while  :-)

**Comment by gadfly361** [comment]
That makes sense to me! Just pushed to clojars :)

**Comment by gadfly361** [comment]
@rej156 This template has been deprecated in favor of [re-frame-template](https://github.com/Day8/re-frame-template), which includes figwheel.
