### ISSUE TITLE
re-frame and routing doubts

### ISSUE THREAD

**Issue by pandeiro** [gadfly361/reagent-seed#4]
Interesting template, thanks @gadfly361!

I have one question about the use of the re-frame approach and one request:

Question: is putting the "page" components [directly in the db](https://github.com/gadfly361/reagent-seed/blob/master/src/leiningen/new/reagent_seed/src/cljs/handlers.cljs#L13) a good approach? This makes the db non-serializable, right (components being functions)? I usually take the approach of routes `assoc`ing a specific key to the db and then the views dispatching on that. I'm wondering if you have any thoughts on the tradeoffs involved.

Request: (somewhat related) I'd like to see how to handle a route that contains parameters. Would those just get dispatched after the component (eg `(dispatch [:update-page some/page param-1 param-2])`, with this approach? Maybe it's just me but I found that non-obvious enough to maybe warrant one such case in the template, to show how it's done.

This is not a real issue as such, more of an attempt to clarify. Thanks again and to @mike-thompson-day8 for all the work and documentation with re-frame. A lot of good ideas.

**Comment by mike-thompson-day8** [comment]
@pandeiro I agree, I wouldn't put the components themselves in the db.  I only ever like to see pure data dispatched. Stuff that I could log - not functions/components.

I recently jotted down a few ideas here:
https://github.com/Day8/re-frame/wiki/A-Larger-App
Please feel free to add thoughts in there.  I'm slightly surprised there hasn't been more community input into that Wiki - I must be doing something wrong. :-)

**Comment by pandeiro** [comment]
@mike-thompson-day8 When I look at all the development and contributors on re-frame and re-con, I come to exactly the opposite conclusion. ;-)

I'd like to contribute to the Wiki but I'm still feeling things out, myself. I kind of wish we had a #reagent on freenode so thoughts could be bounced back and forth rapidly.

Another issue -- which is germane to this template, as well -- is that one seemingly must `:require` the `subs.cljs` and `handlers.cljs` that are suggested in the "A-Larger-App" page, otherwise how do those `register-*` function invocations ever get executed? Is that worth documenting on that page? (And in this template?) Or am I wrong about this?

**Comment by mike-thompson-day8** [comment]
@pandeiro Very good point.  I should have mentioned that.  I've updated:  https://github.com/Day8/re-frame/wiki/A-Larger-App#theres-a-gotcha

**Comment by gadfly361** [comment]
Thanks for the input! Just pushed new version of template with updates drawing from [A Larger App](https://github.com/Day8/re-frame/wiki/A-Larger-App) wiki.

@pandeiro Try using secretary's [parameter destructuring](https://github.com/gf3/secretary#parameter-destructuring) and then passing the params into whatever dispatch function(s) you want.

Here is a silly example:

* Create application

```
$ lein new reagent-seed route-params
```

* Navigate to `src/cljs/route_params/routes.cljs` and change the about route in place to the following

```clojure
(defroute "/about/:id" [id]
  (re-frame/dispatch [:set-active-panel :about-panel])
  (re-frame/dispatch [:set-id id]))
```

* Navigate to `src/cljs/route_params/handlers.cljs` and add a `:set-id` handler

```clojure
(re-frame/register-handler
 :set-id
 (fn [db [_ id]]
   (assoc db :id id)))
```

* Navigate to `src/cljs/route_params/subs.cljs` and add an `:id` subscription

```clojure
(re-frame/register-sub
 :id
 (fn [db _]
   (reaction (:id @db))))
```

* Navigate to `src/cljs/route_params/core.cljs` and subscribe to the `:id` subscription

```clojure
(defn app []
  (let [active-panel (re-frame/subscribe [:active-panel])
        id (re-frame/subscribe [:id])]
    (fn []
      [re-com/v-box
       :height "100%"
       :children [(views/panels @active-panel)
                  [:div "This id is " @id]]])))
```

* Open a terminal and compile the files

```
$ lein cljsbuild once
```

* Start a server

```
$ lein ring server
```

* Navigate to http://localhost:3000/#/about/361 and you should see the phrase "This id is 361" displayed.

Let me know if this isn't what you were hoping for!

**Comment by pandeiro** [comment]
@gadfly361 No, that is awesome! Thanks for the detailed explanation. I'll close this to keep the Issues list clean but it's a great reference for others.

**Comment by gadfly361** [comment]
Thanks, glad it helped!
